Feature Branch for Microverse portfolio project
Spacelama587/Portfolio-Hero pull request #1
Opened 2023-05-31 17:46 UTC by Spacelama587

This is the pull request for Portfolio: setup and mobile first
The project includes hero section for mobile view of the portfolio project

2023-05-31 18:52 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @DevaWinner , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 18:52 UTC, ademibowale commented on index.html
> +        <p class="description">
- [ ] Its very essential and maandatory to stick to figma design ,i would suggest you to add  the backgrund image just like the orignal figma design to make your website look professional.
- [ ] your design
![Screenshot 2023-05-31 190629](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b4f3cb0f-9c90-44d3-8553-11e305572952)

- [ ] figma template
![figma temp](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b1e6580d-9e9b-4ad3-960f-fa8885d82a81)

2023-05-31 18:52 UTC, ademibowale commented on style.css
> +  width: 100%;
- [ ] I would kindly suggest you to align the the The hamburger button  and logo button you can add magin top to hambuger button to be at same top with the logp button .
- [ ] your design
![Screenshot 2023-05-31 190629](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b4f3cb0f-9c90-44d3-8553-11e305572952)

- [ ] figma template
![figma temp](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b1e6580d-9e9b-4ad3-960f-fa8885d82a81)

2023-05-31 18:52 UTC, ademibowale commented on style.css
> +}
- [ ] Its very essential and maandatory to stick to figma design ,i would suggest you to add  the backgrund image just like the orignal figma design to make your website look professional.
- [ ] your design
![Screenshot 2023-05-31 190629](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b4f3cb0f-9c90-44d3-8553-11e305572952)

- [ ] figma template
![figma temp](https://github.com/Spacelama587/Portfolio-Hero/assets/92458236/b1e6580d-9e9b-4ad3-960f-fa8885d82a81)

2023-06-01 09:45 UTC, NahnahAJ commented
## Project Status: INVALIDATED :red_circle: 
Hi @Spacelama587 , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project, that has some linter checks failing. So please fix them and ensure that all your linters are passing :+1: 
- Your linter checks
![image](https://github.com/Spacelama587/Portfolio-Hero/assets/102699958/4320c7ef-f91f-47ae-858f-17646ebd948c)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-01 11:23 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Spacelama587   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following GitHubflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:
- [ ] I kindly request that you adhere to the Figma design provided for your project. The Figma design serves as a visual reference and guideline for implementing the desired user interface and overall look of your application. Please ensure that the implemented code aligns with the design specifications provided in Figma. This includes aspects such as layout, color scheme, typography, and any other visual elements defined in the design.
- [ ] Your Design
![image](https://github.com/Spacelama587/Portfolio-Hero/assets/68823331/2b1cdd96-2092-4b39-bdce-d314c8bb318a)

- [ ] Microverse Figma Design

![image](https://github.com/Spacelama587/Portfolio-Hero/assets/68823331/bb2685a9-3fe6-4062-837b-5a0120eb3fb4)

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 11:23 UTC, Cabraham1 commented on index.html
> +        </div>
- [ ] I Kindly suggest you  Change the `<div>` tag to a `<nav>` tag that aligns with the project requirement and improves semantic markup for navigation. Good suggestion!

2023-06-01 11:23 UTC, Cabraham1 commented on index.html
> +          </ul>
- [ ] To ensure the functionality of your social icons and enable visitors to access your designated social domains, I highly recommend updating the links.
- [ ] replaced the href attribute values (#) with the appropriate URLs for each social platform. You need to replace your_twitter_username, your_instagram_username, and your_linkedin_username with your actual usernames or profile URLs on those platforms.

2023-06-01 14:18 UTC, roshan-bajgain approved these changes
Hi @Spacelama587, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 14:18 UTC, roshan-bajgain commented on index.html
> +        </div>
- [ ] [Optional] I would suggest you please use the `nav` inplace of the `div` tag for semantics reasons and the right position for convention and user experience for mobile devices. As this requirement was not introduced by the first reviewer.

2023-06-01 14:18 UTC, roshan-bajgain commented on index.html
> +    </section>
- [ ] [Optional] This is you last review so I am giving it an optional please implement it. I would suggest please describe the gap between the `p` tag and icons.
### Your design
![his](https://github.com/Spacelama587/Portfolio-Hero/assets/81727988/0e4ad514-6a6f-442b-a644-a88cb6f2876e)

2023-06-01 15:35 UTC, merged