Portfolio project desktop version
Spacelama587/Portfolio-Hero pull request #6
Opened 2023-06-09 15:18 UTC by Spacelama587

Pull request Portfolio project desktop version. 

Used media queries to make sure that your website displays correctly on desktop screens.

2023-06-09 16:23 UTC, frank1738 requested changes
Hi @Spacelama587 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 16:23 UTC, frank1738 commented on index.html
>          <div class="work2tag-html">
- [ ] Looks like some parts of your mobile work section cards were affected after making the desktop version. Kindly address them

![image](https://github.com/Spacelama587/Portfolio-Hero/assets/98453979/c145e997-6ca5-436f-aefa-cf410bab41fb)

2023-06-10 05:25 UTC, Johnadibe requested changes
# Status: Required Changes ♻️
### Hi @Spacelama587🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Implemented some changes requested by the previous reviewer✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 05:25 UTC, Johnadibe commented on index.html
>          <div class="work2tag-html">
> [ ] Good job implementing some of the changes requested by the previous reviewer👍, Nevertheless, I observed that the initial mobile work section card does not align correctly with the Figma design on the mobile version. Could you kindly address this issue? Doing so would greatly enhance the user experience and overall satisfaction.😊
> 
> Figma design:
> 
> ![address1](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/b2cb5d5f-4b45-4376-b27e-0f436718ca8c)
> 
> Your design:
> 
> ![address](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/05f42b02-a3fe-4ec8-822c-32a2c98e61fd)
>

2023-06-10 05:25 UTC, Johnadibe commented on index.html
>        <button class="resume-btn">Get My Resume</button>
> [OPTIONAL] Since the previous code reviewer didn't mention it, I recommend using the same font family as the one used in the Figma design. By following the Figma design closely, you'll maintain consistency throughout various pages and elements, resulting in a coherent and expected interface for users. It would also be great if you could make sure that the "See More" and "Get My Resume" buttons have hover and pressed button state interactions.👍
> 
> Figma design:
> 
> ![address-2-1](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/613db98d-aef7-4e1e-82b2-9e5a7afa405e)
> 
> Button Interactions:
> 
> ![address-2-1-1](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/efeea9bd-9de4-4b38-896e-b16287088f25)
> 
> Your design:
> 
> ![address-2](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/30af5a24-83f9-4e1c-bcc2-cdc1f5351245)
>

2023-06-10 05:25 UTC, Johnadibe commented on style.css
> +  }
> [OPTIONAL] Please make sure to address the issue of white spacing above the hero section, as it was not mentioned by the previous code reviewer. This adjustment is necessary to ensure that the design aligns with the provided Figma design. By closely following the Figma design, you will maintain consistency throughout various pages and elements, creating a cohesive and predictable interface for users.👍
> 
> Figma design:
> 
> ![address-1-1](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/4d901cd1-ab29-4342-acb8-cb3474220434)
> 
> Your design:
> 
> ![address-1](https://github.com/Spacelama587/Portfolio-Hero/assets/40009354/070b8258-5c09-4443-816f-28e054ad1071)
>

2023-06-10 06:27 UTC, abdulhamiid requested changes
Hi @Spacelama587 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linters, Kindly ensure fix the issues, The use of linters helps to diagnose and fix technical issues—e.g. code smells—in the code. As a result, fewer defects make their way to production


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 07:51 UTC, Kossi-stack requested changes
## Hi @Spacelama587,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-10 07:51 UTC, Kossi-stack commented on index.html
> +        <div class="desktop-menu">
- [ ] Kindly fix the navbar they are text, not an image.

- [ ] Figma design
<img width="1393" alt="Screenshot 2023-06-10 at 00 36 43" src="https://github.com/Spacelama587/Portfolio-Hero/assets/81444338/34759928-3a2a-4df5-92b0-4cbef3d2accc">

- [ ] Your Design
<img width="1420" alt="Screenshot 2023-06-10 at 00 35 57" src="https://github.com/Spacelama587/Portfolio-Hero/assets/81444338/fd66e6f0-52ab-401b-95e0-84c447ef1bae">

2023-06-10 07:51 UTC, Kossi-stack commented on style.css
> +  #form-section {
- [ ] Kindly fix this issue for the contact section please follow the design guideline carefully

- [ ] Figma design
<img width="1440" alt="Screenshot 2023-06-10 at 00 32 38" src="https://github.com/Spacelama587/Portfolio-Hero/assets/81444338/49c69e50-9740-43b5-ba01-972c3c4fed26">

- [ ] Your design
<img width="1440" alt="Screenshot 2023-06-10 at 00 33 05" src="https://github.com/Spacelama587/Portfolio-Hero/assets/81444338/b73daf1f-2438-4c80-8b79-4b293012cb92">

2023-06-10 07:56 UTC, Spacelama587 commented on index.html
> +        <div class="desktop-menu">
The images are in svg format, It should load easily on a live server

2023-06-10 09:27 UTC, shella12 requested changes
Hi @Spacelama587, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Great design implementation ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 09:27 UTC, shella12 commented on style.css
> +  #form-section {
- [ ] As suggested by the previous reviewer please adjust the design of your contact form to match the figma template by:
- [ ] Making the form fields align `left` or `flex-start` instead of `center `


|Figma design | Your design|
|---|---|
|<img width="334" alt="Screenshot 2023-06-10 at 2 13 28 PM" src="https://github.com/Spacelama587/Portfolio-Hero/assets/44798044/d1aa7ed0-4f77-4e00-a87d-514217824093">|<img width="334" alt="Screenshot 2023-06-10 at 2 10 48 PM" src="https://github.com/Spacelama587/Portfolio-Hero/assets/44798044/7aadd609-b987-4e34-83cf-14747ab787be">|

2023-06-10 09:27 UTC, shella12 commented on index.html
> +        <p>get in touch.</p>
- [ ] As mentioned by the previous reviewer you need to make sure your contact form follows the figma design. For that I would suggest inclose the whole text in a single paragraph tag instead of multiple tags and align the text to the left and not center: Example snippet

```html

       <p>
        I'm always interested
        in hearing about new 
        projects,so if you'd 
        like to chat please 
        get in touch.</p>

```

|Figma design | Your design|
|---|---|
|<img width="314" alt="Screenshot 2023-06-10 at 2 24 59 PM" src="https://github.com/Spacelama587/Portfolio-Hero/assets/44798044/624c437a-4c31-44ca-a284-01746d76dee0">|<img width="422" alt="Screenshot 2023-06-10 at 2 24 07 PM" src="https://github.com/Spacelama587/Portfolio-Hero/assets/44798044/8df7756a-10f2-4ea5-990e-cb1abce1d51f">|

2023-06-10 11:17 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @Spacelama587👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented all changes requested by the previous reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 12:11 UTC, merged