Create Popup window task
Spacelama587/Portfolio-Hero pull request #9
Opened 2023-06-23 15:16 UTC by Spacelama587

Features Implemented 

When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.
All information in the popup window is is created dynamically using information stored in Javascript array

2023-06-23 15:42 UTC, Strangeal reviewed
Hi @Spacelama587, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] It appears that the project was intended to be completed using pair programming. However, based on the commit history, it seems that you completed the project alone instead of collaborating with your coding partner. For the purpose of maintaining the integrity of the pair programming process, I kindly request you to reach out to your coding partner and work together on the project before resubmitting it for review.  

   - [ ] In case you encountered any difficulties or issues with your coding partner that prevented you from collaborating, I encourage you to contact Student Success ([Success@microverse.org](mailto:Success@microverse.org)) to address the situation and seek assistance. It's important to adhere to the principles of pair programming and communicate any challenges you may face in order to ensure a fair and effective learning environment.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-23 16:55 UTC, Spacelama587 commented
![Screenshot_20230623_222410_Chrome](https://github.com/Spacelama587/Portfolio-Hero/assets/81617658/f2bcc62b-d0e7-4e71-8abb-fdcb228d04b8)

2023-06-23 17:19 UTC, Efiamotu-1 requested changes
Hi @Spacelama587 , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 17:19 UTC, Efiamotu-1 commented on index.html
- [ ] The image for each popup should be dynamically displayed just like every other content. Currently what you have is a single image shwoing for all project, however each project has its own image and this should be what is shown once the user clicks to see the project. please kindly make this desired change so that your popup implementation can be complete. you have done a great job already :+1: :sparkles: 
- > see this project's example image below
- Expected pop-up
![img](https://github.com/mahammad-mostafa/personal-portfolio-site/assets/89055502/d855f972-c144-41ba-a987-0c88e7937b95)
- Your pop-up
![view](https://github.com/alexansaa/Personal_Portafolio/assets/89055502/db103029-790f-4ae9-a82b-1fbbc48ed1ed)

2023-06-23 17:19 UTC, Efiamotu-1 commented on index.html
- [ ] Your current design for mobile version is not so responsive please kindly work on this before resubmitting :+1: 
- your design
![res](https://github.com/Spacelama587/Portfolio-Hero/assets/89055502/6901e6e3-51ef-49c1-8494-66fa44dd888d)

2023-06-23 17:19 UTC, Efiamotu-1 commented on index.html
- As shown in the project requirement below, all of your works card should be generated dynmaically using JavaScript rather than throgh html like you are currently doing. To achieve this you would make use of the projects array you have created and dynamically loop through its contents to display them on the webpage when the page loads. 
- [ ] I suggest that you kindly ensure the buttons in the popup are links which can be visited to view the project's live version or github repository
- Please make sure to make this change and good job on creating the popup correctly. :+1: :sparkles: 
- > project requirement
![nm](https://github.com/mryeminthu/Portfolio/assets/89055502/8e631956-9377-4e7c-8225-dd3d180b166b)

2023-06-23 17:19 UTC, Efiamotu-1 commented on index.html
- [ ] Only the first card from this image has the popup functionality, this shouldn't be the way to implement the popup as the popup should affect every single work card so that once it is clicked it displays the popup. :+1: 
- your design
![cv](https://github.com/Spacelama587/Portfolio-Hero/assets/89055502/4d64dd4f-0712-413b-af7f-3d2c6c46d848)

2023-06-23 17:19 UTC, Efiamotu-1 commented on script.js
> +};
- [ ] Your projects should be an array of objects and because you are to display at least 7 projects you are expected to have 7 objects in the array. However from your codebase you currently only have one object for the project. please kindly work on this before resubmitting your project :+1:
- > see the example below of how it should be
```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]

```

2023-06-24 17:00 UTC, franclobo reviewed
Hi @Spacelama587, 

# Invalid Code Review Request

![descarga](https://github.com/Spacelama587/Portfolio-Hero/assets/58642949/2525cc35-19fc-406a-b4d8-d397b9dfe99c)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has ESLint linter errors ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-26 09:59 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @Spacelama587 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please take note that since you're repeating the block and this is a pair-programming activity with an unapproved PR you'll have to submit a new PR with the commits from your new coding partner according to Microverse's policy.
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-26 10:48 UTC, wayungi reviewed
Hi @Spacelama587 , 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a pair programming project that is invalid because you have done it all alone. Since you are repeating the week and the project is not approved yet, please create a fresh PR and include a screenshot of the message you received from students success in the new PR summary.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-26 11:25 UTC, closed without merging